target-version = "py313"
line-length = 100

[lint]
select = [
    "E",   #  errors
    "W",   # warnings
    "F",   # pyflakes
    "I",   # isort
    "UP",  # pyupgrade
]
ignore = [
    "E501",  # line too long — handled by formatter
]

[lint.isort]
known-first-party = ["src"]


[format]
quote-style = "double"
indent-style = "space"
